Add predict alphafold domain
jpquast/protti pull request #182
Opened 2022-09-17 21:37 UTC by jpquast

Added new `predict_alphafold_domain()` function to protti. 
Updated vignette to include description for the two new functions.

2022-09-18 11:56 UTC, jpquast commented
Now also fixed a bug in `assign_missingness()`: Unequal number of replicates for comparisons are detected and correctly dealt with now.

2022-09-27 14:57 UTC, dschust-r requested changes
Added just two comments 🐨

2022-09-28 07:20 UTC, dschust-r requested changes
Minor comment, otherwise LGTM 🌾

2022-09-28 07:20 UTC, dschust-r commented on R/fetch_mobidb.R
> +#' Fetches information about disordered and mobile protein regions from MobiDB.
```suggestion
#' Fetches information about disordered and flexible protein regions from MobiDB.
```

2022-09-28 07:20 UTC, dschust-r commented on R/fetch_mobidb.R
> +#' @return A data frame that contains start and end positions for disordered and mobile protein
```suggestion
#' @return A data frame that contains start and end positions for disordered and flexible protein
```

2022-09-29 14:03 UTC, dschust-r requested changes
Found a typo 😮

2022-09-29 14:03 UTC, dschust-r commented on R/assign_missingness.R
> +      strwrap("The following comparisons have been detected to have unqueal replicate numbers.
```suggestion
      strwrap("The following comparisons have been detected to have unequal replicate numbers.
```

2022-09-29 14:16 UTC, dschust-r approved these changes
LGTM 🐩

2022-09-29 18:26 UTC, merged