Create synthetic data
jpquast/protti pull request #93
Opened 2021-01-18 15:35 UTC by jpquast

Bug fixes and major updates in many functions. Also new tests and a `create_synthetic_data` function.

2021-01-19 14:33 UTC, dschust-r requested changes
Added a few comments but the rest looks good to me! Seems like you've been quite busy lately :D

2021-01-19 14:33 UTC, dschust-r commented on R/qc_ids.R
> +#' Check number of precursor, preptide or protein IDs
*peptide

2021-01-19 14:33 UTC, dschust-r commented on man/go_enrichment.Rd
> +or \code{plot_cutoff = "adj_pval 0.01"}. The threshold can be choosen freely.}
*chosen

2021-01-19 14:33 UTC, dschust-r commented on man/qc_ids.Rd
> +\title{Check number of precursor, preptide or protein IDs}
*peptide

2021-01-19 16:47 UTC, jpquast commented on R/go_enrichment.R
>      ggplot2::scale_fill_manual(values = c(Down = "#56B4E9", Up = "#E76145")) +
I would do it red and blue to symbolise up and down. could also be red and green (even though you do not know that color) or so. But would keep it like this.

2021-01-19 16:50 UTC, jpquast commented on R/barcode_plot.R
>  {
you mean in addition to `fold_change_cutoff`? or to color peptides in general according to their p-value? this should already be possible using `colouring`.

2021-01-19 18:00 UTC, jpquast commented on R/barcode_plot.R
>  {
can you check if it works well like this now?

2021-01-19 20:04 UTC, dschust-r commented on R/barcode_plot.R
> -#' fold_change = diff,
Just realized that you forgot 'data' in the example

2021-01-19 20:05 UTC, dschust-r commented on R/barcode_plot.R
>  {
Besides the comment on the example, the function works well now.

2021-01-19 20:09 UTC, dschust-r requested changes
Added one small comment to barcode_plot, where in the example you forgot 'data'. Other than that: LGTM

2021-01-20 09:35 UTC, dschust-r approved these changes

2021-01-20 09:36 UTC, merged